import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'router.dart';

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
      title: 'Darkord',
      themeMode: ThemeMode.dark,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        scaffoldBackgroundColor: const Color(0xfff9f9f9),
        canvasColor: const Color(0xfff9f9f9),
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff000000),
          surfaceTint: Color(0xff5e5e5e),
          onPrimary: Color(0xffffffff),
          primaryContainer: Color(0xff262626),
          onPrimaryContainer: Color(0xffb1b1b1),
          secondary: Color(0xff5e5e5e),
          onSecondary: Color(0xffffffff),
          secondaryContainer: Color(0xffe6e6e6),
          onSecondaryContainer: Color(0xff4a4a4a),
          tertiary: Color(0xff000000),
          onTertiary: Color(0xffffffff),
          tertiaryContainer: Color(0xff262626),
          onTertiaryContainer: Color(0xffb1b1b1),
          error: Color(0xffba1a1a),
          onError: Color(0xffffffff),
          errorContainer: Color(0xffffdad6),
          onErrorContainer: Color(0xff410002),
          surface: Color(0xfff9f9f9),
          onSurface: Color(0xff1b1b1b),
          onSurfaceVariant: Color(0xff4c4546),
          outline: Color(0xff7e7576),
          outlineVariant: Color(0xffcfc4c5),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xff303030),
          inversePrimary: Color(0xffc6c6c6),
          primaryFixed: Color(0xffe2e2e2),
          onPrimaryFixed: Color(0xff1b1b1b),
          primaryFixedDim: Color(0xffc6c6c6),
          onPrimaryFixedVariant: Color(0xff474747),
          secondaryFixed: Color(0xffe2e2e2),
          onSecondaryFixed: Color(0xff1b1b1b),
          secondaryFixedDim: Color(0xffc6c6c6),
          onSecondaryFixedVariant: Color(0xff474747),
          tertiaryFixed: Color(0xffe2e2e2),
          onTertiaryFixed: Color(0xff1b1b1b),
          tertiaryFixedDim: Color(0xffc6c6c6),
          onTertiaryFixedVariant: Color(0xff474747),
          surfaceDim: Color(0xffdadada),
          surfaceBright: Color(0xfff9f9f9),
          surfaceContainerLowest: Color(0xffffffff),
          surfaceContainerLow: Color(0xfff3f3f3),
          surfaceContainer: Color(0xffeeeeee),
          surfaceContainerHigh: Color(0xffe8e8e8),
          surfaceContainerHighest: Color(0xffe2e2e2),
        ),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xff131313),
        canvasColor: const Color(0xff131313),
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xffc6c6c6),
          surfaceTint: Color(0xffc6c6c6),
          onPrimary: Color(0xff303030),
          primaryContainer: Color(0xff000000),
          onPrimaryContainer: Color(0xff969696),
          secondary: Color(0xffc6c6c6),
          onSecondary: Color(0xff303030),
          secondaryContainer: Color(0xff3d3d3d),
          onSecondaryContainer: Color(0xffd1d1d1),
          tertiary: Color(0xffc6c6c6),
          onTertiary: Color(0xff303030),
          tertiaryContainer: Color(0xff000000),
          onTertiaryContainer: Color(0xff969696),
          error: Color(0xffffb4ab),
          onError: Color(0xff690005),
          errorContainer: Color(0xff93000a),
          onErrorContainer: Color(0xffffdad6),
          surface: Color(0xff131313),
          onSurface: Color(0xffe2e2e2),
          onSurfaceVariant: Color(0xffcfc4c5),
          outline: Color(0xff988e90),
          outlineVariant: Color(0xff4c4546),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xffe2e2e2),
          inversePrimary: Color(0xff5e5e5e),
          primaryFixed: Color(0xffe2e2e2),
          onPrimaryFixed: Color(0xff1b1b1b),
          primaryFixedDim: Color(0xffc6c6c6),
          onPrimaryFixedVariant: Color(0xff474747),
          secondaryFixed: Color(0xffe2e2e2),
          onSecondaryFixed: Color(0xff1b1b1b),
          secondaryFixedDim: Color(0xffc6c6c6),
          onSecondaryFixedVariant: Color(0xff474747),
          tertiaryFixed: Color(0xffe2e2e2),
          onTertiaryFixed: Color(0xff1b1b1b),
          tertiaryFixedDim: Color(0xffc6c6c6),
          onTertiaryFixedVariant: Color(0xff474747),
          surfaceDim: Color(0xff131313),
          surfaceBright: Color(0xff393939),
          surfaceContainerLowest: Color(0xff0e0e0e),
          surfaceContainerLow: Color(0xff1b1b1b),
          surfaceContainer: Color(0xff1f1f1f),
          surfaceContainerHigh: Color(0xff2a2a2a),
          surfaceContainerHighest: Color(0xff353535),
        ),
      ),
    );
  }
}
